# Generated by Django 5.2.8 on 2025-12-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id_plat', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('Entrée', 'Entrée'), ('Plat principal', 'Plat principal'), ('Dessert', 'Dessert'), ('Boisson', 'Boisson')], max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
