# Generated by Django 5.2.8 on 2025-12-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_de_Menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plats/'),
        ),
    ]
