# Generated by Django 5.2.8 on 2026-01-08 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_de_Menu', '0002_plat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveBigIntegerField()),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_de_Menu.plat')),
            ],
        ),
    ]
