# Generated by Django 5.2.8 on 2026-01-10 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_de_Menu', '0003_vente'),
        ('Gestion_de_Vente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_globales', to='Gestion_de_Menu.plat'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
